<!DOCTYPE html>
<html>
<head>
    <title>Foundation 实例</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/resources/css/foundation.min.css">
    
    <style type="text/css">
        @media (max-width: 480px) {
            .small-device {
                display: none;
            }
        }
        .color-blue {color: #09A1AD;}
        .blog-post { border-bottom: 1px dashed rgba(134, 25, 55, 0.62); margin-bottom: 15px;}
        .blog-post:last-child { border-bottom: none; margin-bottom: 15px;}
        .blog-post h3 {border-left: 5px solid #cffecf; padding-left: 10px;}
        .blog-post p {text-indent: 2em;}
        /*.blog-post:hover { border: 1px solid rgba(134, 25, 55, 0.62);}*/

    </style>

</head>
<body>

    <div class="fixed">
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="javascript:;">Weekly</a></h1>
                </li>
                <!-- 小屏幕上折叠按钮: 去掉 .menu-icon 类，可以去除图标。
               如果需要只显示图片，可以删除 "Menu" 文本 -->
                <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
            </ul>

            <section class="top-bar-section">
                <ul class="left">
                    <li><a href="active">首页</a></li>
                    <li><a href="#">编程语言</a></li>
                    <li><a href="#">技术杂谈</a></li>
                    <li><a href="#">生活百味</a></li>
                </ul>

                <ul class="right">
                    <li><a href="#">Sign</a></li>
                    <li><a href="#">Login</a></li>
                </ul>
            </section>
        </nav>
        <ul class="breadcrumbs">
            <li><a href="#">首页</a></li>
            <li class="current">Vacation</li>
        </ul>
    </div>



    <!-- Context Start -->
    <div class="row" id="content">

        <!-- Left -->
        <div class="medium-8 columns">
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>


            <div class="pagination-centered">
                <ul class="pagination">
                    <li class="arrow"><a href="#">«</a></li>
                    <li class="current"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li class="arrow"><a href="#">»</a></li>
                </ul>
            </div>

        </div>
        <!-- Left -->


        <!-- Right -->
        <div class="medium-3 columns content-right small-device" data-sticky-container>
            <div class="sticky" data-sticky data-anchor="content">
                <h4>分类</h4>
                <ul>
                    <li><a href="#">PHP杂烩</a></li>
                    <li><a href="#">Java</a></li>
                    <li><a href="#">Javascript</a></li>
                    <li><a href="#">Linux</a></li>
                </ul>
                <h4>标签</h4>
                <ul>
                    <li><a href="#">Python</a></li>
                    <li><a href="#">数据</a></li>
                    <li><a href="#">Nosql</a></li>
                    <li><a href="#">mysql</a></li>
                </ul>
            </div>
        </div>
        <!-- Right -->

    </div>
    <!-- Context End -->








<script src="/resources/js/vendor/jquery.min.js"></script>
<script src="/resources/js/foundation.min.js"></script>
<script src="/resources/js/vendor/modernizr.js"></script>

<!-- 初始化 Foundation JS -->
<script>
    $(document).ready(function() {
        $(document).foundation();
    })
</script>

</body>
</html>
