<!DOCTYPE html>
<html>
<head>
    <title>Foundation 实例</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/resources/css/foundation.min.css">
<!--    <link rel="stylesheet" href="/resources/css/common.css">-->
<!--    <link rel="stylesheet" href="/resources/css/index.css">-->

</head>
<body>

    <div class="fixed">
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="javascript:;">Weekly</a></h1>
                </li>
                <!-- 小屏幕上折叠按钮: 去掉 .menu-icon 类，可以去除图标。
               如果需要只显示图片，可以删除 "Menu" 文本 -->
                <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
            </ul>

            <section class="top-bar-section">
                <ul class="left">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Page 1</a></li>
                    <li><a href="#">Page 2</a></li>
                    <li><a href="#">Page 3</a></li>
                </ul>

                <ul class="right">
                    <li><a href="#">Sign</a></li>
                    <li><a href="#">Login</a></li>
                </ul>
            </section>
        </nav>
        <ul class="breadcrumbs">
            <li><a href="#">Home</a></li>
            <li><a href="#">Private</a></li>
            <li class="unavailable"><a href="#">Pictures</a></li>
            <li class="current">Vacation</li>
        </ul>
    </div>



    <!-- Context Start -->
    <div class="row" id="content">
        <div class="medium-8 columns">
            <div class="blog-post callout">
                <h3 class="bm-line">MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3>
                <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
                <p><em>导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p>
            </div>
        </div>

    </div>
    <!-- Context End -->









<script src="/resources/js/vendor/jquery.min.js"></script>
<script src="/resources/js/foundation.min.js"></script>
<script src="/resources/js/vendor/modernizr.js"></script>

<!-- 初始化 Foundation JS -->
<script>
    $(document).ready(function() {
        $(document).foundation();
    })
</script>

</body>
</html>
