<!DOCTYPE html>
<html>
<head>
    <title>WEEKLY - 周末记录</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/resources/css/foundation.min.css">
    <link rel="stylesheet" href="/resources/editor.md/css/editormd.css">
    <!--    <link rel="stylesheet" href="/resources/css/common.css">-->
    <!--    <link rel="stylesheet" href="/resources/css/index.css">-->

    <style type="text/css">
        body {background: rgba(204, 204, 204, 0.42);}
        @media (max-width: 480px) {
            .small-device {
                display: none;
            }
        }
        .color-blue {color: #09A1AD;}
        .blog-post { border-bottom: 1px dashed rgba(134, 25, 55, 0.62); margin-bottom: 15px;}
        .blog-post:last-child { border-bottom: none; margin-bottom: 15px;}
        /*.blog-post h3 {border-left: 5px solid #cffecf; padding-left: 10px;}*/
        .blog-post h3 {text-align: center;}
        .blog-post p {text-indent: 2em;}
        /*.blog-post:hover { border: 1px solid rgba(134, 25, 55, 0.62);}*/

    </style>

</head>
<body>

<div class="fixed">
    <nav class="top-bar" data-topbar>
        <ul class="title-area">
            <li class="name">
                <h1><a href="javascript:;">Weekly</a></h1>
            </li>
            <!-- 小屏幕上折叠按钮: 去掉 .menu-icon 类，可以去除图标。
           如果需要只显示图片，可以删除 "Menu" 文本 -->
            <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>

        <section class="top-bar-section">
            <ul class="left">
                <li><a href="active">首页</a></li>
                <li><a href="#">编程语言</a></li>
                <li><a href="#">技术杂谈</a></li>
                <li><a href="#">生活百味</a></li>
            </ul>

            <ul class="right">
                <li><a href="#">Sign</a></li>
                <li><a href="#">Login</a></li>
            </ul>
        </section>
    </nav>
    <ul class="breadcrumbs">
        <li><a href="#">首页</a></li>
        <li class="current">Vacation</li>
    </ul>
</div>



<!-- Context Start -->
<div class="row" id="content">
	
	<!-- <button id="btn-preview">预览</button>
	<button id="fullscreen-btn">Fullscreen (Press ESC cancel)</button> -->

    <!-- Left -->
    <div class="medium-12 columns">
        <div class="blog-post callout">
            <!-- <h3>MongoDB 3.0 副本集搭建 <small>3/6/2015</small></h3> -->
            <!--<img class="thumbnail" src="http://placehold.it/850x350">-->
            <!-- <p><em class="color-blue">导读：</em>复制是在多台服务器之间同步数据的过程。复制集在大多数场合下已经代替Master-Slave复制。如果可能的话，尽可能使用复制集而不是主-从复制架构。</p> -->

            <div id="editormd">
		        <textarea style="display:none;">### Hello Editor.md !</textarea>
		    </div>
        </div>
  

    </div>
    <!-- Left -->


    <!-- Right -->
    <!-- <div class="medium-4 columns content-right small-device" data-sticky-container>
        <div class="sticky" data-sticky data-anchor="content">
            <h4>分类</h4>
            <ul>
                <li><a href="#">PHP杂烩</a></li>
                <li><a href="#">Java</a></li>
                <li><a href="#">Javascript</a></li>
                <li><a href="#">Linux</a></li>
            </ul>
            <span class="label">Default Label</span>
            <span class="label secondary">Secondary Label</span>
            <span class="label success">Success Label</span>
            <span class="label info">Info Label</span>
            <span class="label warning">Success Label</span>
            <span class="label alert">Alert Label</span>
        </div>
    </div> -->
    <!-- Right -->

</div>
<!-- Context End -->


<!-- <div class="row">
    <footer class="columns small-device">
        Footer
    </footer>
</div> -->



<script src="/resources/js/vendor/jquery.min.js"></script>
<script src="/resources/js/foundation.min.js"></script>
<script src="/resources/js/vendor/modernizr.js"></script>
<script src="/resources/editor.md/editormd.js"></script>

<!-- 初始化 Foundation JS -->
<script>
    $(document).ready(function() {
        $(document).foundation();
    })
</script>
<script type="text/javascript">
	var editor;
    $(function() {
        $.get('/resources/test.md', function (md) {
        editor = editormd("editormd", {
                // path : "/resources/editor.md/lib/", // Autoload modules mode, codemirror, marked... dependents libs path
                // width: "90%",
                height: "100%",
                // theme : "dark",
                // previewTheme : "dark",
                // editorTheme : "pastel-on-dark",
                markdown : md,
                // codeFold : true,
                // syncScrolling : false,
                // saveHTMLToTextarea : true,    // 保存 HTML 到 Textarea
                // searchReplace : true,
                // watch : false,                // 关闭实时预览
                // htmlDecode : "style,script,iframe|on*",            // 开启 HTML 标签解析，为了安全性，默认不开启
                // toolbar  : false,             //关闭工具栏
                // // previewCodeHighlight : false, // 关闭预览 HTML 的代码块高亮，默认开启
                // emoji : true,
                // taskList : true,
                // tocm            : true,         // Using [TOCM]
                // tex : true,                   // 开启科学公式TeX语言支持，默认关闭
                // flowChart : true,             // 开启流程图支持，默认关闭
                // sequenceDiagram : true,       // 开启时序/序列图支持，默认关闭,
                // dialogLockScreen : false,   // 设置弹出层对话框不锁屏，全局通用，默认为true
                // dialogShowMask : false,     // 设置弹出层对话框显示透明遮罩层，全局通用，默认为true
                // dialogDraggable : false,    // 设置弹出层对话框不可拖动，全局通用，默认为true
                // dialogMaskOpacity : 0.4,    // 设置透明遮罩层的透明度，全局通用，默认值为0.1
                // dialogMaskBgColor : "#000", // 设置透明遮罩层的背景颜色，全局通用，默认为#fff
                // imageUpload : true,
                // imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
                // imageUploadURL : "./php/upload.php",
                // onload : function() {
                //     console.log('onload', this);
                //     // this.fullscreen();
                //     // this.watch();
                //     // this.watch().fullscreen();
                //     this.previewing();
                //     // this.preview();
                //     //this.setMarkdown("#PHP");
                //     //this.width("100%");
                //     //this.height(480);
                //     //this.resize("100%", 640);
                // }

            });
        });

		$("#btn-preview").click(function () {
			editor.previewing();
		});

		$("#fullscreen-btn").bind('click', function() {
            editor.fullscreen();
        });

        

    });
</script>

</body>
</html>
